name: Automation

on:
  repository_dispatch:
    types: [on-demand-docker-build]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PYTHON_VERSION=${{ github.event.client_payload.PYTHON_VERSION }}
            POETRY_VERSION=${{ github.event.client_payload.POETRY_VERSION }}
            MKDOCS_VERSION=${{ github.event.client_payload.MKDOCS_VERSION }}
            MKDOCS_BUILD_PLANTUML_VERSION=${{ github.event.client_payload.MKDOCS_BUILD_PLANTUML_VERSION }}
            PLANTUML_VERSION=${{ github.event.client_payload.PLANTUML_VERSION }}
          tags: |
            andreiolar1/python-poetry-mkdocs:${{ github.event.client_payload.PYTHON_VERSION }}-${{ github.event.client_payload.POETRY_VERSION }}-${{ github.event.client_payload.MKDOCS_VERSION }}
            andreiolar1/python-poetry-mkdocs:latest
          push: true

