name: build-docker-image
on:
  workflow_dispatch:
    inputs:
      python:
        default: 3.11.4
        required: true
      poetry:
        default: 1.5.1
        required: true
      mkdocs:
        default: 1.5.2
        required: true
      mkdocs_plantuml:
        default: 1.7.4
        required: true
      plantuml:
        default: 1.2023.10
        required: true    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install yq
        uses: dcarbone/install-yq-action@v1.1.0
      - name: git checkout
        uses: actions/checkout@v2
      - name: set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PYTHON_VERSION=${{inputs.python}}
            POETRY_VERSION=${{inputs.poetry}}
            MKDOCS_VERSION=${{inputs.mkdocs}}
            MKDOCS_BUILD_PLANTUML_VERSION=${{inputs.mkdocs_plantuml}}
            PLANTUML_VERSION=${{inputs.plantuml}}
          push: true
          tags: |
            andreiolar1/python-poetry-mkdocs:latest
            andreiolar1/python-poetry-mkdocs:${{inputs.python}}-${{inputs.poetry}}-${{inputs.mkdocs}}
