name: build-docker-image
on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      python:
        default: 3.11.4
        required: true
        description: python version
      poetry:
        default: 1.5.1
        required: true
        description: poetry version
      mkdocs:
        default: 1.5.2
        required: true
        description: mkdocs version
      mkdocs_plantuml:
        default: 1.7.4
        required: true
        description: mkdocs plugin for plantuml version
      plantuml:
        default: 1.2023.10
        required: true    
        description: plantuml version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install yq
        uses: dcarbone/install-yq-action@v1.1.0
      - name: git checkout
        uses: actions/checkout@v2
      - name: set up QEmu
        uses: docker/setup-qemu-action@v2
      - name: set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PYTHON_VERSION=${{inputs.python}}
            POETRY_VERSION=${{inputs.poetry}}
            MKDOCS_VERSION=${{inputs.mkdocs}}
            MKDOCS_BUILD_PLANTUML_VERSION=${{inputs.mkdocs_plantuml}}
            PLANTUML_VERSION=${{inputs.plantuml}}
          push: true
          tags: |
            andreiolar1/python-poetry-mkdocs:latest
            andreiolar1/python-poetry-mkdocs:${{github.ref_name}}
