name: build-docker-image
on:
  workflow_dispatch:
    inputs:
      build-args:
        type: string
        description: Python version
        default: PYTHON_VERSION=3.11.4 POETRY_VERSION=1.5.1 MKDOCS_VERSION=1.5.2 MKDOCS_BUILD_PLANTUML_VERSION=1.7.4 PLANTUML_VERSION=1.2023.10
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install yq
        uses: dcarbone/install-yq-action@v1.1.0
      - name: git checkout
        uses: actions/checkout@v2
      - name: set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: ${{inputs.build-args}}
          push: true
          tags: andreiolar1/python-poetry-mkdocs:latest
